gitSourceBranch = "main"

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

# From git:
organizationName = "ryanlin"
projectName = "moonwave-test"
url = "https://ryanlin.github.io"
baseUrl = "/moonwave-test/"
tagline = ""